mysite/blogapp/urls.py
from django.conf.urls import patterns, url, include
from blogapp import views
urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
        url(r'^update/',  views.update, name='update'),
        url(r'^delete/',  views.delete, name='delete'),
        url(r'^update/',  views.update, name='update'),
        url(r'^mysubmit/',  views.mysubmit, name='mysubmit'),
        url(r'^register/', views.register, name='register'),
        
	)

mysite/mysite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^flow_drawer/',include('flow_drawer.urls',namespace="flow_drawer")),
    url(r'^blog/',include('blogapp.urls',namespace="blogapp")),
)

mysite/blogapp/models.py
from django.db import models
from mongoengine import *
from mysite.settings import DBNAME

connect(DBNAME)

class Post(Document):
    title = StringField(max_length=120, required=True)
    test_type = StringField(max_length=100, required=True)
    content = StringField(max_length=500, required=True)
    last_update = DateTimeField(required=True)

mysite/blogapp/views.py
from django.shortcuts import render
from django.views.decorators.cache import cache_page
from django.core.cache import cache

# Create your views here.
from django.shortcuts import render_to_response
from django.template import RequestContext
from models import Post
import datetime



def index(request):
    kk = ''
    if request.method == 'POST':
       # save new post
       title = request.POST['title']
       test_type = request.POST['test_type']
       content = request.POST['content']
       post = Post(title=title)
       post.last_update = datetime.datetime.now() 
       post.test_type = test_type
       post.content = content
       
       post.save()
       kk = "123"
    # Get all posts from DB
    posts = Post.objects 
    return render_to_response('index.html', {'abc': kk},
                              context_instance=RequestContext(request))


def update(request):
    id = eval("request." + request.method + "['id']")
    post = Post.objects(id=id)[0]
    
    if request.method == 'POST':
        # update field values and save to mongo
        post.title = request.POST['title']

        post.last_update = datetime.datetime.now() 
        post.content = request.POST['content']
        post.save()
        template = 'index.html'
        params = {'Posts': Post.objects} 

    elif request.method == 'GET':
        template = 'update.html'
        params = {'post':post}
   
    return render_to_response(template, params, context_instance=RequestContext(request))
                              

def delete(request):
    id = eval("request." + request.method + "['id']")

    if request.method == 'POST':
        post = Post.objects(id=id)[0]
        post.delete() 
        template = 'mysubmit.html'
        params = {'Posts': Post.objects} 
    elif request.method == 'GET':
        template = 'delete.html'
        params = { 'id': id } 

    return render_to_response(template, params, context_instance=RequestContext(request))

def mysubmit(request):
    if request.method == 'POST':
       # save new post
       title = request.POST['title']
       test_type = request.POST['test_type']
       content = request.POST['content']
       post = Post(title=title)
       post.last_update = datetime.datetime.now() 
       post.test_type = test_type
       post.content = content
       
       post.save()

    # Get all posts from DB
    posts = Post.objects 
    return render_to_response('mysubmit.html', {'Posts': posts},
                              context_instance=RequestContext(request))


import uuid


  #read cache user id
def read_from_cache():
    key = datetime
    reg_id = cache.get(key)
    return reg_id

#write cache user id
def write_to_cache(data):
    key = datetime
    cache.set(key, data, 60*1)

def get_id():
  return  str(uuid.uuid4())[:11].replace('-', '').lower() 

@cache_page(30)
def register(request):
    reg_id = get_id
    write_to_cache(reg_id)
    #return  render_to_response('register.html', {'reg_id': 1234})
    return render_to_response('register.html', {'reg_id': reg_id},
                              context_instance=RequestContext(request))

mysite/blogapp/templates/delete.html
<!-- delete.html -->
<!DOCTYPE html>
<html>
  <head>
    <link href="{{STATIC_URL}}blog.css" rel="stylesheet" type="text/css">  
  </head> 
  <body>
    <h1>Blongo - Delete Entry</h1>
    <form method="post" action="{% url 'blogapp:delete' %}">
      {% csrf_token %}
      <input type="hidden" name="id" value="{{id}}">
      <p>Are you sure you want to delete this post?</p>
      <input type="submit" value="Delete">
    </form>
  </body>
</html>

mysite/blogapp/templates/index.html
<!-- index.html -->
<!DOCTYPE html>
<html>
  <head>
    <link href="{{STATIC_URL}}blog/blog.css" rel="stylesheet" style="text/css">
    <script type="text/javascript" src="{{ STATIC_URL }}blog/blog.js"></script>
    <title>My blog</title>
  </head> 
  <body>
    <div id="wrapper">
    <header>Blog</header>
    <nav>
      <ul>
	<li>
	  <a href="{% url 'blogapp:index' %}"  id="home_page">
	   Home Page {{ abc }}
	  </a>
	</li>
	<li>
	  <a href="{% url 'blogapp:index' %}" id="picture">
	    Picture
	  </a>
	</li>
	<li>
	  <a href="{% url 'blogapp:index' %}" id="video">
	    Video
	  </a>
	</li>
	<li>
	  <a href="{% url 'blogapp:index' %}"id="car">
	    Car
	  </a>
	</li>
	<li>
	  <a href="{% url 'blogapp:mysubmit' %}" id="my_submit" onclick="loadMysubmit();">
	    My Submit
	  </a>
	</li>
      </ul>
    </nav>
      <section>
	<form method="post" action="{% url 'blogapp:mysubmit' %}">
	  {% csrf_token %}
	  

	  <p><label id="title-label">Title:</label><input id="title-box"type="text" name="title" placeholder="TR Title" required></p>
	  
	  
	  <p>
	    <label id="test-type-label">Test Type: </label>
	    <select id="test-type-box" name="test_type" >
	      <option value="function-test" selected>Function Test</option>
	      <option value="system-test" >System Test</option>
	      <option value="unite-test" >Unite Test</option>
	    </select>
	  </p>
	  
	  
	  <p>
	    <textarea name="content" placeholder="Enter Content" rows=5 cols=50 required>
            </textarea></br>
          </p>
	<input type="submit" value="Add Post">
	
	</form>

      </section>
    </div>
  </body>
</html>

mysite/blogapp/templates/mysubmit.html
<!-- index.html -->
<!DOCTYPE html>
<html>
  <head>
    <link href="{{STATIC_URL}}blog/blog.css" rel="stylesheet" style="text/css">
    <script type="text/javascript" src="{{ STATIC_URL }}blog/blog.js"></script>
    <title>My blog</title>
  </head> 
  <body>
    <div id="wrapper">
    <header>Blog</header>
    <nav>
      <ul>
	<li>
	  <a href="{% url 'blogapp:index' %}"  id="home_page">
	   Home Page
	  </a>
	</li>
	<li>
	  <a href="{% url 'blogapp:index' %}" id="picture">
	    Picture
	  </a>
	</li>
	<li>
	  <a href="{% url 'blogapp:index' %}" id="video">
	    Video
	  </a>
	</li>
	<li>
	  <a href="{% url 'blogapp:index' %}"id="car">
	    Car
	  </a>
	</li>
	<li>
	  <a href="{% url 'blogapp:index' %}" id="my_submit" onclick="loadMysubmit();">
	    My Submit
	  </a>
	</li>
      </ul>
    </nav>
      
      <section>
	<!-- Cycle through entries -->
	{% for post in Posts %}
	<h2> {{ post.title }} </h2>
	<p>{{ post.last_update }}</p>
	<p>{{ post.test_type }} </p>
	<p>{{ post.content }}</p>
	<form method="get" action="{% url 'blogapp:update' %}">
          <input type="hidden" name="id" value="{{ post.id }}">
        <input type="hidden" name="title" value="{{ post.title }}">
	<input type="hidden" name="test_type" value="{{ post.test_type }}">
        <input type="hidden" name="last_update" value="{{ post.last_update }}">
        <input type="hidden" name="content" value="{{ post.content }}">
        <input type="submit" name="" value="update">
	</form>
	<form method="get" action="{% url 'blogapp:delete' %}">
          <input type="hidden" name="id" value="{{post.id}}">
          <input type="submit" value="delete">
	</form>
      {% endfor %}
	
      </section>
    <p>{{ abc }}</p>
    </div>
  </body>
</html>

mysite/blogapp/templates/register.html
your register id is : {{ reg_id }}

<div class="textwidget">
        
        <script charset="Shift_JIS" src="http://chabudai.sakura.ne.jp/blogparts/honehoneclock/honehone_clock_wh.js"></script>
        <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0" width="160" height="70" id="honehoneclock" align="middle"><param name="allowScriptAccess" value="always"><param name="movie" value="http://chabudai.sakura.ne.jp/blogparts/honehoneclock/honehone_clock_wh.swf"><param name="quality" value="high"><param name="bgcolor" value="#ffffff"></object>
        
    </div>

mysite/blogapp/templates/update.html
<!-- update.html -->
<!DOCTYPE html>
<html>
  <head>
    <link href="{{STATIC_URL}}blog.css" rel="stylesheet" type="text/css">
  </head> 
  <body>
    <h1>Blongo - Update Entry</h1>
    <form method="post" action="{% url 'blogapp:update' %}">
      {% csrf_token %}
      <ul>
        <li><input type="hidden" name="id" value="{{post.id}}"></li>
        <li>
          <input type="text" name="title" placeholder="Post Title" 
             value="{{post.title}}" required>
          <input type="text" name="last_update" 
             value="{{post.last_update}}" required>
        </li>
        <li>
          <textarea name="content" placeholder="Enter Content" 
            rows=5 cols=50 required>
            {{post.content}}
          </textarea>
        </li>
        <li>
          <input type="submit" value="Save Changes">
        </li>
      </ul>
    </form>
  </body>
</html>