mysite/flow_drawer/urls.py
from django.conf.urls import patterns, url, include
from flow_drawer import views
urlpatterns = patterns('',
	# ex: /flow_drawer/
	url(r'^$', views.index, name='index'),
	)
	

mysite/mysite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^flow_drawer/',include('flow_drawer.urls',namespace="flow_drawer")),
    url(r'^blog/',include('blogapp.urls',namespace="blogapp")),
)

mysite/flow_drawer/models.py
from django.db import models

# Create your models here.
class FlowDrawer(models.Model):
	flow = models.CharField(max_length=200)

mysite/flow_drawer/views.py
# Create your views here.
from django.shortcuts import render, get_object_or_404
from flow_drawer.models import FlowDrawer
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from collections import OrderedDict
import re

def index(request):
	signal_flow_code = []
        message_and_signal = []
        message = []
        signal = []
        network_element_all = ''
        network_element = ''
        space_add = ''
        line_one  = ''
        line_draw = []
        signal_flow = ''
        types = ''
        tmp = []
	tmp_message = ''
        direction_line = ''
        arrow_line = list()
        tmp_list_signal = list()
        final_arrow_line = list()
        dict_line = dict()
        dict_arrow = dict()
        direction = list()
        try :
                if 'signal_flow_code' in request.POST:
                        tmp = str(request.POST['signal_flow_code']).split('\r\n')
                        network_element = tmp.pop(0).split('@')[1]
                        message_and_signal = tmp
        except :
                network_element = ''
                
        list_network_element = network_element.split()
        final_line = network_element
        
        for i in list_network_element:
                line_draw.append(len(i)/2 * ' ' + '|' + (len(i)-len(i)/2-1)*' ')
                
        dict_line =dict(zip(list_network_element,line_draw))
        
        for i in range(len(dict_line.keys())):
                final_line = final_line.replace(dict_line.keys()[i],dict_line.values()[i],1)
                
        #Get the messages and signal from the context
        last_one_is_arrow = 1
        no_blank_line = 1
        for context_num in range(len(message_and_signal)):
                if '->' in message_and_signal[context_num]:
                        signal.append(message_and_signal[context_num])
                else:
                        if message_and_signal[context_num] :
                                try :
                                        if '->' in message_and_signal[context_num + 1] :
                                                message.append(message_and_signal[context_num])
                                                message.append('no_blank_line')
                                        else :
                                                message.append(message_and_signal[context_num])
                                except IndexError :
                                        message.append(message_and_signal[context_num])
                        else :
                                message.append(message_and_signal[context_num])
        try :
                for item in range(len(message)) :
                        if not message[0] :
                                message.pop(0)
                        elif message[0] :
                                break
        except IndexError :
                message = []
        
        #End of Get the message and signal from context

        for count in range(len(signal)):
                tmp_list_signal.append(signal[count].strip().split('->'))
        
        for signal_count in range(len(tmp_list_signal)):
                if tmp_list_signal[0]:
                        if list_network_element.index(tmp_list_signal[signal_count][0]) < list_network_element.index(tmp_list_signal[signal_count][1]):
                                direction.append('forward')
                        elif list_network_element.index(tmp_list_signal[signal_count][0]) > list_network_element.index(tmp_list_signal[signal_count][1]):
                                direction.append('backward')
                        else:
                                direction.append('wrong')
                        

        #Draw the arrow line

        for signal_count in range(len(tmp_list_signal)): 
                j = 0
                list_signal = list()
                dict_arrow = dict_line.copy()
                if direction[signal_count]== 'forward':
                        for item in tmp_list_signal[signal_count]:
                                for ne in dict_arrow.keys():
                                        if item == ne :
                                                if  j == 0:
                                                        list_signal.append(len(ne)/2 * ' ' + '|' + (len(ne)-len(ne)/2-1) * '-' )
                                                elif j == 1:
                                                        list_signal.append((len(ne)/2-1) * '-' + '>' + '|' + (len(ne)-len(ne)/2-1) * ' ' )
                                                dict_arrow[ne] = list_signal[j]
                                                j = j +1

                        d = list_signal
                        final_arrow_line.append(network_element)
                        for element in dict_arrow.keys():
                                final_arrow_line[signal_count] = final_arrow_line[signal_count].replace(element,dict_arrow[element],1)
                                final_arrow_line[signal_count] = re.sub("\-[\-\| ]*\>", lambda x:x.group(0).replace('|',' ').replace(' ','-'), final_arrow_line[signal_count])
                                                
                elif direction[signal_count] == 'backward':
                        for item in tmp_list_signal[signal_count]:
                                for ne in dict_arrow.keys():
                                        if item == ne :
                                                if  j == 1:
                                                        list_signal.append(len(ne)/2 * ' ' + '|' + '<' + (len(ne)-len(ne)/2-2) * '-' )
                                                elif j == 0:
                                                        list_signal.append((len(ne)/2) * '-' + '|'  + (len(ne)-len(ne)/2-1) * ' ' )
                                                dict_arrow[ne] = list_signal[j]
                                                j = j +1
                        d = list_signal
                        final_arrow_line.append(network_element)
                        for element in dict_arrow.keys():
                                final_arrow_line[signal_count] = final_arrow_line[signal_count].replace(element,dict_arrow[element],1)
                                final_arrow_line[signal_count] = re.sub("\<[\-\| ]*\-", lambda x:x.group(0).replace('|',' ').replace(' ','-'), final_arrow_line[signal_count])

        # Draw arrow line end
        
        #Bind the messages to its signal
        message_count = 0
        dict_all_context = OrderedDict()
        tmp_arrow_related_message = []
        arrow_count = 0
        for arrow_count in range(len(final_arrow_line)):
                if final_arrow_line[arrow_count]:
                        try :                
                                while message[message_count] :
                                        if message[message_count] == 'no_blank_line' :
                                                message_count = message_count + 1
                                                break
                                        else :
                                                tmp_arrow_related_message.append(message[message_count])                                        
                                                message_count = message_count + 1
                                while not message[message_count] :
                                        tmp_arrow_related_message.append(final_line)
                                        message_count = message_count + 1
                        except  IndexError :
                                tmp_arrow_related_message = tmp_arrow_related_message
                                


                        dict_all_context[final_arrow_line[arrow_count]] = list(tmp_arrow_related_message)  #should use a = list(b) instead of a = b ,as the second will make a equals b all the time.
                tmp_arrow_related_message = list()
        #End of bind the messages to its signal

        #Construct the list of arrow_line and its messages

        list_all_context = list()
        length = 0
        message_template = ''
        for keys in dict_all_context.keys() :
                blank_lines = list()
                for items in dict_all_context[keys]:
                        rex = r"[\-\>\<]+"
                        matched_str  = re.compile(rex).search(keys).group(0)
                        if not  items == final_line :
                                if matched_str :
                                        length= len(matched_str)
                                        message_template = items.center(length)
                                        items = re.sub(rex, message_template, keys)
                                        list_all_context.append(items)
                        else :
                                blank_lines.append(items)

                list_all_context.append(keys)

                for line in blank_lines :
                        list_all_context.append(line)
                                                
        #end of list_all_context
        

	context ={'network_element': network_element,
                  'final_line': final_line,
                  'times': range(10),
                  'message': message,
                  'final_arrow_line': final_arrow_line,
                  'a': message_count,
                  'c': tmp_list_signal,
                  'd': 'kk',
                  'b': dict_arrow,
                  'list_all_context': list_all_context ,
#                  'tmp_arrow_related_message': ,
                  'message_count' : message_count,
                  'arrow_count' : arrow_count,
                  'dict_all_context_values' : dict_all_context.values(),
                  'dict_all_context_keys' : dict_all_context.keys(),

mysite/flow_drawer/templates/flow_drawer/index.html
<head>
  <style type="text/css">
   h1 {
        color:blue;
        font-weight:strong;



   }
  </style>


  <script type="text/javascript" src="{{ STATIC_URL }}/cookie.js"></script>
  <script type="text/javascript">
    var firstload = 1;
    //    document.getElementById("txt1").defaultValue = "good";

    function saveContent(){
    eraseCookie("SFcode_content");
    var content;
    content = document.getElementById("txt1").value;
    //        alert("init content:"+ content);
    //alert("save content");
    if (navigator.cookieEnabled){
    content = content.replace(/\r\n|\r|\n/g,'magic',1);
    //alert("content:\r" + content);
    writeCookie("SFcode_content", content, 5 * 365);
    }
    else
    alert("Cookie is not enabled");
    firstload = 0;
    //alert("first load = "+ firstload);
    
    }    
    
    function recoverContent(){
    var content;  
    if (navigator.cookieEnabled){
    //    alert("Cookie is ok");
    content = readCookie("SFcode_content");
    content = content.replace(/magic/g,'\r\n',1);
    //alert("recover content");
    //alert("content:\r" + content);
    }
    else
    alert("Cookie is not enabled");
    //        alert("show content:\n" + content);
    document.getElementById("txt1").value = content;
    //alert("content:\r" +     document.getElementById("txt1").value);
    }
    
    function reloadContent(){
    //alert("reload Content");
    saveContent();
    recoverContent();
}

    function resetContent(){
    if (firstload){
    document.getElementById("txt1").value = "@AAAA                     BBBBB                                  CCC                        DDDDDD \n" +
    "\n" +
    "AAAA->CCC\n" +
    "aa \n" +
    "\n" +
    "DDDDDD->BBBBB\n" +
    "bb \n" +
    "\n" +
    "CCC->DDDDDD\n" +
    "cc \n" +
    "\n" +    
    "BBBBB->AAAA\n" +
    "dd \n";
    //alert("close window");

    content = document.getElementById("txt1").value;
    //alert("init content:"+ content);
    if (navigator.cookieEnabled){
    content = content.replace(/\r\n|\r|\n/g,'magic',1);
    //            alert("content:\r" + content);
    writeCookie("SFcode_content", content, 5 * 365);
    }
    }
    else {
    recoverContent();
    }
    }

  </script>
  
  
</head>
<body onload="recoverContent()";>





</br>
<p>
<h1>Signal Flow:</h1>
<pre>
    {{ network_element }}    
    {% for item in list_all_context %}
    {{ item }}{% endfor %}


</br>
dict_line:
{{ dict_line }}
<!-- used for debug
    {{ network_element }}    
    {% for item in tmp_arrow_related_message %}
    {{ item }}{% endfor %}

</br>    
Final_arrow_line:
    {% for item in final_arrow_line %}
    {{ item }}{% endfor %}

A:
    {{ a }}

Dict_Context:
    {% for item in dict_all_context %} 
    {{ item }}
    {% endfor %}


All_Context:
    {% for item in list_all_context %}
    {{ item }}{% endfor %}

Keys:
    {{ dict_all_context_keys }}
</p>





 </br>
 </br>
 <p>
   Signal:</br>
   {% for i in signal %}
   {{ i }}</br></br>
   {% endfor %}
 </p>


 <p>Message:</br>
 {{ message }}

end of debug -->

</pre>
 </p>
 </br>
 </br>
 <h1> signal_flow_code: </h1>
 </br>
 {% for item in signal_flow %}
 {{ item }}
 {% endfor %}
 <form action="{% url 'flow_drawer:index' %}" method="post">

 {% csrf_token %}
 <textarea class=saveHistory  id='txt1' name="signal_flow_code" style="width: 100%; height:300px"></textarea>
 <input type="submit" value="SF Code -> SF" onclick="reloadContent();"/>
 </form>

 </body>

mysite/flow_drawer/templates/flow_drawer/results.html
<h1>{{ poll.question }}</h1>
<ul>
	{% for choice in poll.choice_set.all %}
		<li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
	{% endfor %}
</ul>
<a href="{% url 'polls:detail' poll.id %}">Vote again?</a>
<a href="{% url 'polls:index' %}"> Home </a>